import { Tree, logger, readProjectConfiguration } from '@nrwl/devkit';
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';

export default async function(tree: Tree, schema: any) {
  const projectSrcRoot = readProjectConfiguration(tree, schema.name).sourceRoot;
  logger.info(`Creating build information for project - ${ schema.name }`);
  return () => {
    createVersionsFile(tree, projectSrcRoot + '/environments/build.ts');
  };
}

function createVersionsFile(tree: Tree, filename: string) {
  const date = new Date();
  const revision = execSync('git rev-parse --short HEAD').toString().trim();
  const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
  const version = require(tree.root + '/package.json').version;
  logger.info(`Date: ${ date }\nVersion: '${ version }'\nRevision: '${ revision }'\nBranch: '${ branch }'`);

  const content = `// this file is automatically generated by the build-information generator
export const build = {
  date: '${ date }',
  version: '${ version }',
  revision: '${ revision }',
  branch: '${ branch }'
};`;

  writeFileSync(filename, content);
}
