
// this file is automatically generated by the build-information generator
export const build = {
  date: 'Wed Feb 16 2022 16:18:55 GMT+0100 (Central European Standard Time)',
  version: '0.0.0',
  revision: 'ecc0464',
  branch: 'master'
};
