// this file is automatically generated by the build-information generator
export const build = {
	date: 'Sat Apr 16 2022 19:41:01 GMT+0200 (Central European Summer Time)',
	version: '0.0.0',
	revision: '321e62a',
	branch: 'master'
};
